name = "test1"
compatibility_date = "2024-02-10"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "visitbook-db"
database_id = "08d3170d-3975-4554-8315-4330f9c0d469"
